/* Autogenerated by png2wx.pl on Tue Jan 26 10:13:07 2021 */
#ifndef BITMAP_H
#define BITMAP_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_conan_icon;

#endif /* BITMAP_H */
