name: basic-wxwidgets-OSX-build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install conan
        run: |
          pip install conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

      - name: Install libraries
        run: |
          mkdir ${{github.workspace}}/basic_wxwidgets/bin
          cd ${{github.workspace}}/basic_wxwidgets/bin
          conan install ..

      - name: Build
        run: |
          cd ${{github.workspace}}/basic_wxwidgets/bin
          conan build ..
          cpack -G DragNDrop

      - name: upload file
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.dmg;bin/*.dmg"
          tags: true
          draft: true