name: basic-wxwidgets-Windows-build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install conan
        run: |
          pip install conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

      - name: Install libraries
        run: |
          mkdir ${{github.workspace}}/basic_wxwidgets/bin
          cd ${{github.workspace}}/basic_wxwidgets/bin
          conan install ..

      - name: Build
        run: |
          cd ${{github.workspace}}/basic_wxwidgets/bin
          conan build ..
          dir
          dir ${{github.workspace}}/basic_wxwidgets/bin/bin
          cp ${{github.workspace}}/basic_wxwidgets/bin/bin/*.exe ${{github.workspace}}
          dir 

      - name: upload file
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.exe;bin/dist/*.exe;bin/*.exe"
          tags: true
          draft: true
